# Generated by Codex on 2026-04-20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlackjackSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('player_turn', 'Player Turn'), ('dealer_turn', 'Dealer Turn'), ('finished', 'Finished')], default='player_turn', max_length=20)),
                ('outcome', models.CharField(choices=[('pending', 'Pending'), ('win', 'Win'), ('loss', 'Loss'), ('push', 'Push'), ('mixed', 'Mixed'), ('blackjack', 'Blackjack')], default='pending', max_length=20)),
                ('bet_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('total_wagered', models.DecimalField(decimal_places=2, max_digits=18)),
                ('payout_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('net_result', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('player_hands', models.JSONField(default=list)),
                ('dealer_cards', models.JSONField(default=list)),
                ('deck', models.JSONField(default=list)),
                ('current_hand_index', models.PositiveIntegerField(default=0)),
                ('result_message', models.CharField(blank=True, max_length=255)),
                ('client_seed', models.CharField(blank=True, max_length=128)),
                ('server_seed', models.CharField(max_length=128)),
                ('server_seed_hash', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blackjack_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('top_up', 'Top Up'), ('bet', 'Bet'), ('payout', 'Payout')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=18)),
                ('description', models.CharField(max_length=255)),
                ('game_type', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='games.blackjacksession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={'ordering': ['-created_at']},
        ),
    ]
